---
- name: Install cups-client
  apt:
    name: cups-client
    state: present

- name: Configure cups client
  template:
    src: cups/client.conf
    dest: /etc/cups/client.conf
    owner: root
    group: lp
    mode: u=rw,g=r,o=r
