---
- name: Get package facts
  package_facts:
    manager: auto

- name: Download .deb files
  get_url:
    url: "{{ item.url }}"
    dest: /tmp
    checksum: "{{ item.checksum | default('') }}"
  with_items: "{{ useful_deb_packages }}"
  when: item.name not in ansible_facts.packages
  register: deb_files

- name: Install useful deb packages
  apt:
    deb: "{{ item.dest }}"
    state: present
  with_items: "{{ deb_files.results }}"
  when: item.dest is defined

- name: Remove downloaded .deb files
  file:
    path: "{{ item.dest }}"
    state: absent
  with_items: "{{ deb_files.results }}"
  when: item.dest is defined
