---
- name: Install desktop environment
  ansible.builtin.apt:
    name: "{{ desktop_env }}"
    state: present

- name: Install display manager
  ansible.builtin.apt:
    name: "{{ desktop_dm }}"
    state: present

- name: Remove gnome-initial-setup
  ansible.builtin.apt:
    name: gnome-initial-setup
    state: absent

- name: Configure Xsession
  ansible.builtin.template:
    src: display/Xsession
    dest: /etc/X11/Xsession
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  notify: restart display manager

- name: Configure display manager
  ansible.builtin.template:
    src: display/dm.conf
    dest: "{{ desktop_dms[desktop_dm].file }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart display manager

- name: Set display manager
  ansible.builtin.copy:
    content: "{{ desktop_dms[desktop_dm].path }}\n"
    dest: /etc/X11/default-display-manager
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: apply display manager
