---
- name: Install desktop environment
  apt:
    name: "{{ desktop_env }}"
    state: present

- name: Install display manager
  apt:
    name: "{{ desktop_dm }}"
    state: present

- name: Remove gnome-initial-setup
  ansible.builtin.apt:
    name: gnome-initial-setup
    state: absent

- name: Configure display manager
  template:
    src: display/dm.conf
    dest: "{{ desktop_dms[desktop_dm].file }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart display manager

- name: Set display manager
  copy:
    content: "{{ desktop_dms[desktop_dm].path }}\n"
    dest: /etc/X11/default-display-manager
  notify: apply display manager
