---
- name: Add docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release}} stable
    filename: docker
    update_cache: yes
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present

- name: Add docker service overrides directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Add docker service overrides
  template:
    src: docker/service-overrides.conf
    dest: /etc/systemd/system/docker.service.d/service-overrides.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: systemd daemon-reload

- name: Add docker daemon configuration
  template:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart docker

- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: yes
