---
- import_tasks: cache.yml
  when: desktop_set_cache
- import_tasks: file-indexing.yml
  when: desktop_disable_file_indexing
- import_tasks: snap.yml
- import_tasks: sudoers.yml
- import_tasks: display.yml
- import_tasks: browsers.yml
- import_tasks: printing.yml
- import_tasks: dropbox.yml
