---
- ansible.builtin.import_tasks: nfs.yml
  when: desktop_nfs_home
- ansible.builtin.import_tasks: snap.yml
- ansible.builtin.import_tasks: sudoers.yml
- ansible.builtin.import_tasks: display.yml
- ansible.builtin.import_tasks: browsers.yml
- ansible.builtin.import_tasks: printing/main.yml
- ansible.builtin.import_tasks: dropbox.yml
- ansible.builtin.import_tasks: slack.yml
