---
- import_tasks: nfs.yml
  when: desktop_nfs_home
- import_tasks: snap.yml
- import_tasks: sudoers.yml
- import_tasks: display.yml
- import_tasks: browsers.yml
- import_tasks: printing.yml
- import_tasks: dropbox.yml
- import_tasks: slack.yml
