---
- name: Install nfs-common
  apt:
    name: nfs-common
    state: present
  when: storage_mounts | selectattr('fstype', 'match', 'nfs\d?') | list | length > 0

- name: Mount storage
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts | default(omit) }}"
    state: mounted
  with_items: "{{ storage_mounts }}"
