---
- name: Install bindfs
  ansible.builtin.apt:
    name: bindfs
    install_recommends: no
    state: present

- name: Resolve path to fusermount binary
  ansible.builtin.stat:
    path: /usr/bin/fusermount
  register: _fusermount_bin

- name: Set fusermount bin path when a symlink
  ansible.builtin.set_fact:
    fusermount_symlink_path: "{{ _fusermount_bin.stat.lnk_source }}"
  when: _fusermount_bin.stat.islnk

- name: Set capabilities for fusermount
  community.general.capabilities:
    path: "{{ fusermount_symlink_path | default('/usr/bin/fusermount') }}"
    capability: cap_sys_admin+ep
    state: present

- name: Remove setuid bit from fusermount
  ansible.builtin.file:
    path: "{{ fusermount_symlink_path | default('/usr/bin/fusermount') }}"
    state: file
    owner: root
    group: root
    mode: u-s

- name: Add profile environment scripts
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop:
    - src: profile.d/xdg.cache.sh
      dest: /etc/profile.d/xdg.cache.sh
    - src: profile.d/slack.cache.sh
      dest: /etc/profile.d/slack.cache.sh
    - src: profile.d/disable_file_indexing.sh
      dest: /etc/profile.d/disable_file_indexing.sh
  loop_control:
    label: "{{ item.dest }}"

- name: Create local desktop entry directory
  ansible.builtin.file:
    path: /usr/local/share/applications
    state: directory
    owner: root
    group: root
    mode: u=rxw,g=rx,o=rx

- name: Configure vscode to install extensions in XDG_CACHE_HOME
  ansible.builtin.template:
    src: applications/code.desktop
    dest: /usr/local/share/applications/code.desktop
    owner: root
    group: root
    mode: u=rw,g=r,o=r
