---
- name: Add keys for useful repos
  apt_key:
    url: "{{ item.key.url }}"
    id: "{{ item.key.id | default(omit) }}"
    state: present
  with_items: "{{ useful_repos }}"

- name: Add useful repos
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.name }}"
    update_cache: yes
    state: present
  with_items: "{{ useful_repos }}"
