---
- name: Install useful snap packages
  community.general.snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default('stable') }}"
    classic: "{{ item.classic | default('no') }}"
    state: present
  loop: "{{ snap_packages_install }}"
  loop_control:
    label: "{{ item.name }}"
