---
- name: Configure sudoers
  ansible.builtin.template:
    src: sudoers/sudoers
    dest: /etc/sudoers.d/{{ item.file }}
    owner: root
    group: root
    mode: u=r,g=r,o=
  loop: "{{ sudoers }}"
  loop_control:
    label: "{{ item.file }}"
